# Set keypoint_topic to the name of the topic in which the
# /geometry_msgs/PointStamped msgs are published. Default is 
# set to '/trajectory_points'
keypoint_topic: "/trajectory_points"

# Set variable_timestamp to 'true' if you want to use the timestamp of the
# points in the prediction phase. Otherwise set it to false and the value of
# the 'frequency' parameter will be used accordingly

variable_timestamp: false
frequency: 30

# R and Q matrices for the kalman filter
Rx: 0.02
Ry: 0.04
Rz: 0.012
Q: 0.005
